export const SUCCESS = "SUCCESS";
export const ERROR = "ERROR";

export const NOT_FOUND_STATUS_CODE = 404;
export const SERVER_ERROR_STATUS_CODE = 500;
export const BAD_REQUEST_STATUS_CODE = 400;
export const UNAUTHORIZED_STATUS_CODE = 401;

export const MSG_INVALID_PAGINATION_PARAMS = "MSG_INVALID_PAGINATION_PARAMS";
export const MSG_INVALID_ORGANISATION_ID = "MSG_INVALID_ORGANISATION_ID";
